[package]
name = "img2ascii"
version = "0.1.0"
edition = "2021"
authors = [ "Max Mynter" ]

[dependencies]
clap = {version="4.0", features=["derive"]}
image = {version="0.25"}
colored = {version="3.0.0"}
